### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by PremanandChowdhury** [4nmolChaudhary/GroMRKT-E-Commerce-Grocery-Store#5]
I too have made a e-commerce website but not completed yet. I am stuck with the code that to be written for managing the orders. If you could help me with the same. 
Do ping me.

**Comment by 4nmolChaudhary** [comment]
For sure go ahead

**Comment by PremanandChowdhury** [comment]
I will DM you in telegram for further details.

**Comment by 4nmolChaudhary** [comment]
Okay ..
